controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# homepage
# home:
#     path: /
#     controller: App\Controller\homeController::home