controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# homepage
# homepage:
#     path: /
#     controller: App\Controller\homeController::homepage